name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}
          config: |
            Host ${{ secrets.EC2_HOST }}
              IdentityFile ~/.ssh/id_rsa
              User ${{ secrets.EC2_USERNAME }}
              StrictHostKeyChecking no
          if_key_exists: replace

      - name: Verify SSH key permissions
        run: |
          ls -la ~/.ssh/
          chmod 600 ~/.ssh/id_rsa
          echo "SSH key is set up with proper permissions"

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
